# Generated by Django 5.2 on 2025-08-07 14:00

import django.utils.timezone
import ocr_tts_app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRTTSSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ocr_tts_app.models.upload_to_images,
                    ),
                ),
                ("image_filename", models.CharField(blank=True, max_length=255)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("ocr_error", models.TextField(blank=True)),
                (
                    "tts_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("audio_file_path", models.CharField(blank=True, max_length=500)),
                ("audio_filename", models.CharField(blank=True, max_length=255)),
                ("tts_error", models.TextField(blank=True)),
                ("processing_time_ocr", models.FloatField(blank=True, null=True)),
                ("processing_time_tts", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "OCR TTS Session",
                "verbose_name_plural": "OCR TTS Sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
