# Generated by Django 5.2 on 2025-08-09 06:49

import django.db.models.deletion
import django.utils.timezone
import ocr_tts_app.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_tts_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "learning_type",
                    models.CharField(
                        choices=[
                            ("image_ocr", "Image OCR"),
                            ("text_input", "Direct Text Input"),
                            ("practice", "Practice Session"),
                        ],
                        default="image_ocr",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ocr_tts_app.models.upload_to_images,
                    ),
                ),
                ("image_filename", models.CharField(blank=True, max_length=255)),
                (
                    "ocr_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("ocr_error", models.TextField(blank=True)),
                (
                    "tts_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=ocr_tts_app.models.upload_to_audio,
                    ),
                ),
                ("audio_file_path", models.CharField(blank=True, max_length=500)),
                ("audio_filename", models.CharField(blank=True, max_length=255)),
                ("tts_error", models.TextField(blank=True)),
                ("target_language", models.CharField(default="en", max_length=10)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("word_count", models.PositiveIntegerField(default=0)),
                ("processing_time_ocr", models.FloatField(blank=True, null=True)),
                ("processing_time_tts", models.FloatField(blank=True, null=True)),
                ("times_played", models.PositiveIntegerField(default=0)),
                ("last_played_at", models.DateTimeField(blank=True, null=True)),
                ("is_favorited", models.BooleanField(default=False)),
                (
                    "user_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Session",
                "verbose_name_plural": "Learning Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("sessions_completed", models.PositiveIntegerField(default=0)),
                ("words_learned", models.PositiveIntegerField(default=0)),
                ("time_spent_minutes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Statistics",
                "verbose_name_plural": "Learning Statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                        ],
                        default="English",
                        max_length=10,
                    ),
                ),
                (
                    "voice_preference",
                    models.CharField(
                        choices=[
                            ("male", "Male Voice"),
                            ("female", "Female Voice"),
                            ("neutral", "Neutral Voice"),
                        ],
                        default="female",
                        max_length=50,
                    ),
                ),
                ("learning_streak", models.PositiveIntegerField(default=0)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("total_words_learned", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("definition", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mastery_level",
                    models.CharField(
                        choices=[
                            ("learning", "Learning"),
                            ("practicing", "Practicing"),
                            ("mastered", "Mastered"),
                        ],
                        default="learning",
                        max_length=20,
                    ),
                ),
                ("times_reviewed", models.PositiveIntegerField(default=0)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "learning_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ocr_tts_app.learninghistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocabulary",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vocabulary Word",
                "verbose_name_plural": "Vocabulary Words",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="OCRTTSSession",
        ),
        migrations.AddIndex(
            model_name="learninghistory",
            index=models.Index(
                fields=["user", "-created_at"], name="ocr_tts_app_user_id_e0c6ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learninghistory",
            index=models.Index(
                fields=["user", "learning_type"], name="ocr_tts_app_user_id_fbd511_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learninghistory",
            index=models.Index(
                fields=["user", "is_favorited"], name="ocr_tts_app_user_id_3736b3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="learningstatistics",
            unique_together={("user", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="vocabulary",
            unique_together={("user", "word", "language")},
        ),
    ]
