# Generated by Django 5.2 on 2025-08-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_tts_app", "0002_learninghistory_learningstatistics_userprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learninghistory",
            name="dictionary_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="learninghistory",
            name="is_single_word",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="learninghistory",
            name="word_definitions",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_language",
            field=models.CharField(
                choices=[("en", "English"), ("zh", "Chinese"), ("ms", "Malay")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="vocabulary",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("zh", "Chinese"), ("ms", "Malay")],
                max_length=10,
            ),
        ),
    ]
